/*
 * ********************************
 * **  GENERATED BY CLAUDE CODE  **
 * ********************************
 *
 * gen_feed — synthetic order-flow generator for the baseline order book.
 *
 * Produces a full session of requests (ORDER / PARTIAL_CANCEL / FULL_CANCEL)
 * for a single instrument under a chosen market regime, and writes TWO files:
 *
 *   <out>.bin  — fixed-size binary Request records (native layout, no
 *                delimiters); the format stream::VectorInStream(fname) reads.
 *   <out>.txt  — a human-readable companion: a summary header plus one aligned
 *                line per request, in the same order as the binary. Line N of
 *                the body corresponds to record N of the .bin.
 *
 * Why a matching model inside the generator?
 *   The generator runs a lightweight price-time-priority book of its own so it
 *   can (a) keep the resting book BOUNDED (a real book has finite depth, not
 *   millions of open orders), and (b) aim cancels at orders that are actually
 *   resting. It does NOT decide the engine's output — the engine re-matches the
 *   emitted feed itself. The internal book only shapes a realistic input.
 *   Emitted ORDER.amt is the order as submitted; the model tracks the residual.
 *
 * Prices are integer ticks (think cents). Deterministic given a seed.
 *
 * Scenarios:
 *   typical      calm, mean-reverting mid, tight spread, balanced flow
 *   volatile     trending/jumpy mid, wide/variable spread, fat-tailed sizes,
 *                directional bursts, high turnover
 *   flash_crash  calm, then a one-sided sell cascade with liquidity withdrawal,
 *                then a recovery leg
 *
 * Build & run (from repo root):
 *   g++ -std=c++23 -I common/include -O2 \
 *       -o /tmp/gen_feed v1_baseline/test/data/gen_feed.cpp
 *   /tmp/gen_feed typical  v1_baseline/test/data/typical      1000000 1
 *   /tmp/gen_feed volatile v1_baseline/test/data/volatile     1000000 2
 *   /tmp/gen_feed flash_crash v1_baseline/test/data/flash_crash 1000000 3
 */

#include <schema.h>

#include <algorithm>
#include <cmath>
#include <cstdio>
#include <cstring>
#include <deque>
#include <fstream>
#include <map>
#include <random>
#include <string>
#include <unordered_map>
#include <vector>

using namespace order_book::common;

// ------------------------------- Request builders --------------------------

static Request make_order(std::uint64_t id, Side side, std::uint64_t price,
						  std::uint64_t amt) {
	Request r;
	std::memset(&r, 0, sizeof r);
	r.order.type = RequestType::ORDER;
	r.order.len = sizeof(Order);
	r.order.order_id = id;
	r.order.side = side;
	r.order.price = price;
	r.order.amt = amt;
	return r;
}

// Cancels carry the side of the order they target: the engine routes on it, so
// it must match the side the order was submitted with.
static Request make_partial_cancel(std::uint64_t id, Side side,
								   std::uint64_t amt) {
	Request r;
	std::memset(&r, 0, sizeof r);
	r.partial_cancel.type = RequestType::PARTIAL_CANCEL;
	r.partial_cancel.len = sizeof(PartialCancel);
	r.partial_cancel.order_id = id;
	r.partial_cancel.side = side;
	r.partial_cancel.amt = amt;
	return r;
}

static Request make_full_cancel(std::uint64_t id, Side side) {
	Request r;
	std::memset(&r, 0, sizeof r);
	r.full_cancel.type = RequestType::FULL_CANCEL;
	r.full_cancel.len = sizeof(FullCancel);
	r.full_cancel.order_id = id;
	r.full_cancel.side = side;
	return r;
}

// ------------------------------- Market regime -----------------------------

enum class Scenario { TYPICAL, VOLATILE, FLASH_CRASH };

struct MarketState {
	double mid;
	double prev_mid;  // previous mid, for the momentum EMA
	double drift;	  // short-term momentum EMA (volatile flow bias)
	std::uint64_t step;
	std::uint64_t total;
};

// Per-step sampling knobs, produced by advancing the market model one tick.
struct StepParams {
	double buy_prob;		  // P(new order is a buy)
	double p_aggressive;	  // P(new order crosses the spread)
	double passive_off_mean;  // mean ticks a passive order rests from mid
	double cross_off_mean;	  // mean ticks an aggressive order crosses past mid
	double size_median;		  // lognormal median order size
	double size_sigma;		  // lognormal sigma (tail heaviness)
	double base_cancel;		  // cancel pressure at target depth
	std::uint64_t target_depth;
};

static double clampd(double x, double lo, double hi) {
	return x < lo ? lo : (x > hi ? hi : x);
}

// Advances st by one step and returns the sampling knobs for this request.
//
// Price dynamics are defined over the NORMALIZED trading day t in [0,1] with
// dt = 1/total, so a run's price path is invariant to the request count: the
// same regime produces the same daily range whether count is 100k or 10M. All
// mid moves use a mean-reverting (Ornstein-Uhlenbeck) form
//     mid += theta*(target - mid)*dt + sigma*sqrt(dt)*N(0,1)
// whose stationary std is sigma/sqrt(2*theta) — independent of dt — which is
// what keeps the range bounded no matter how many steps we take.
static StepParams step_market(Scenario sc, MarketState& st,
							  std::mt19937_64& rng) {
	std::normal_distribution<double> N01(0.0, 1.0);
	std::uniform_real_distribution<double> U01(0.0, 1.0);
	const double center = 10000.0;
	const double dt = 1.0 / static_cast<double>(st.total);
	const double sdt = std::sqrt(dt);
	const double t = static_cast<double>(st.step) / st.total;
	StepParams p{};

	switch (sc) {
		case Scenario::TYPICAL: {
			// Calm: brisk reversion, ~1.5% daily std (sigma/sqrt(2*theta)).
			const double theta = 10.0, sigma = 270.0;
			st.mid += theta * (center - st.mid) * dt + sigma * sdt * N01(rng);
			st.mid = std::max(st.mid, 100.0);
			p = {0.50, 0.22, 3.0, 1.5, 100.0, 0.6, 0.55, 3000};
			break;
		}
		case Scenario::VOLATILE: {
			// Extreme: slow reversion (trends persist ~2/3 of the day) + high
			// vol (~20% daily std) + occasional news shocks (~30/day).
			const double theta = 1.5, sigma = 3500.0;
			st.mid += theta * (center - st.mid) * dt + sigma * sdt * N01(rng);
			if (U01(rng) < 30.0 * dt) st.mid += 300.0 * N01(rng);
			st.mid = std::max(st.mid, 300.0);
			// Flow leans with short-term momentum (trend-following bursts).
			const double delta = st.mid - st.prev_mid;
			st.drift = 0.995 * st.drift + 0.005 * delta;
			st.prev_mid = st.mid;
			p = {clampd(0.5 + 0.3 * std::tanh(st.drift * 20.0), 0.25, 0.75),
				 0.42,
				 8.0,
				 5.0,
				 150.0,
				 1.1,
				 0.55,
				 3000};
			break;
		}
		case Scenario::FLASH_CRASH: {
			// A target price path: calm -> sharp crash to a trough -> partial
			// recovery -> calm. mid tracks the target tightly (large theta), so
			// the crash/recovery are controlled regardless of step count.
			double target;
			if (t < 0.40)
				target = center;
			else if (t < 0.45)
				target = center + (2500.0 - center) * ((t - 0.40) / 0.05);
			else if (t < 0.50)
				target = 2500.0;  // trough (~ -75%)
			else if (t < 0.60)
				target = 2500.0 + (8500.0 - 2500.0) * ((t - 0.50) / 0.10);
			else
				target = 8500.0;  // partial recovery, still below start
			const double theta = 40.0, sigma = 500.0;
			st.mid += theta * (target - st.mid) * dt + sigma * sdt * N01(rng);
			st.mid = std::max(st.mid, 100.0);

			if (t >= 0.40 &&
				t < 0.50)  // cascade: sellers lift, liquidity pulled
				p = {0.15, 0.70, 12.0, 10.0, 200.0, 1.2, 0.85, 3000};
			else if (t >= 0.50 && t < 0.60)	 // recovery: buyers step in
				p = {0.70, 0.45, 6.0, 4.0, 150.0, 0.9, 0.60, 3000};
			else  // calm backdrop
				p = {0.50, 0.22, 3.0, 1.5, 100.0, 0.6, 0.55, 3000};
			break;
		}
	}
	return p;
}

// ------------------------------- Generator ---------------------------------

struct Resting {
	Side side;
	std::uint64_t price;
	std::uint64_t amt;
};

struct Stats {
	std::uint64_t n_order = 0, n_buy = 0, n_sell = 0;
	std::uint64_t n_aggressive = 0;	 // orders that traded on entry
	std::uint64_t n_partial = 0, n_full = 0;
	std::uint64_t sim_trades = 0, sim_volume = 0;
	std::uint64_t max_depth = 0;
	std::uint64_t price_min = ~0ull, price_max = 0, size_max = 0;
	long double size_sum = 0;
	double mid_min = 1e18, mid_max = -1e18, mid_final = 0;
};

int main(int argc, char* argv[]) {
	if (argc < 3) {
		std::fprintf(stderr,
					 "usage: %s <typical|volatile|flash_crash> <out_basename> "
					 "[count=1000000] [seed=1]\n",
					 argv[0]);
		return 1;
	}
	const std::string scen = argv[1];
	const std::string out_base = argv[2];
	const std::uint64_t count =
		argc > 3 ? std::strtoull(argv[3], nullptr, 10) : 1000000ull;
	const std::uint64_t seed =
		argc > 4 ? std::strtoull(argv[4], nullptr, 10) : 1;

	Scenario sc;
	if (scen == "typical")
		sc = Scenario::TYPICAL;
	else if (scen == "volatile")
		sc = Scenario::VOLATILE;
	else if (scen == "flash_crash")
		sc = Scenario::FLASH_CRASH;
	else {
		std::fprintf(stderr, "unknown scenario '%s'\n", scen.c_str());
		return 1;
	}

	std::mt19937_64 rng(seed);
	std::normal_distribution<double> N01(0.0, 1.0);
	std::uniform_real_distribution<double> U01(0.0, 1.0);

	// Generator-side book (bounded, lazy-deleted from price levels).
	std::unordered_map<std::uint64_t, Resting> book;
	std::map<std::uint64_t, std::deque<std::uint64_t>> bids,
		asks;						  // price->FIFO
	std::vector<std::uint64_t> live;  // for cancels
	std::unordered_map<std::uint64_t, std::size_t> live_pos;
	book.reserve(1 << 16);
	live_pos.reserve(1 << 16);

	auto add_live = [&](std::uint64_t id) {
		live_pos[id] = live.size();
		live.push_back(id);
	};
	auto remove_live = [&](std::uint64_t id) {
		auto it = live_pos.find(id);
		if (it == live_pos.end()) return;
		std::size_t i = it->second, last = live.size() - 1;
		std::uint64_t moved = live[last];
		live[i] = moved;
		live_pos[moved] = i;
		live.pop_back();
		live_pos.erase(it);
	};

	std::vector<Request> feed;
	feed.reserve(count);
	Stats s;
	MarketState st{10000.0, 10000.0, 0.0, 0, count};
	std::uint64_t next_id = 0;

	std::lognormal_distribution<double> unit_ln(0.0, 1.0);	// scaled per-step

	for (std::uint64_t k = 0; k < count; ++k) {
		st.step = k;
		StepParams p = step_market(sc, st, rng);
		s.mid_min = std::min(s.mid_min, st.mid);
		s.mid_max = std::max(s.mid_max, st.mid);

		double fill = static_cast<double>(book.size()) / p.target_depth;
		double p_cancel = std::min(0.9, p.base_cancel * fill);

		if (!live.empty() && U01(rng) < p_cancel) {
			// ---- cancel a resting order ----
			std::uint64_t idx = std::uniform_int_distribution<std::uint64_t>(
				0, live.size() - 1)(rng);
			std::uint64_t oid = live[idx];
			Resting& r = book[oid];
			// Read before any erase below invalidates r.
			const Side oside = r.side;
			if (U01(rng) < 0.40 && r.amt > 1) {
				std::uint64_t camt =
					std::uniform_int_distribution<std::uint64_t>(1, r.amt)(rng);
				feed.push_back(make_partial_cancel(oid, oside, camt));
				++s.n_partial;
				r.amt -= camt;
				if (r.amt == 0) {
					remove_live(oid);
					book.erase(oid);
				}
			} else {
				feed.push_back(make_full_cancel(oid, oside));
				++s.n_full;
				remove_live(oid);
				book.erase(oid);
			}
		} else {
			// ---- new order ----
			bool buy = U01(rng) < p.buy_prob;
			Side side = buy ? Side::BUY : Side::SELL;
			bool aggressive = U01(rng) < p.p_aggressive;

			double mid = st.mid;
			std::uint64_t price;
			if (aggressive) {
				double off = p.cross_off_mean * unit_ln(rng);  // >=0
				price = buy ? static_cast<std::uint64_t>(mid + 1 + off)
							: static_cast<std::uint64_t>(
								  std::max(1.0, mid - 1 - off));
			} else {
				double off = p.passive_off_mean * unit_ln(rng);
				price = buy ? static_cast<std::uint64_t>(
								  std::max(1.0, mid - 1 - off))
							: static_cast<std::uint64_t>(mid + 1 + off);
			}

			double sz = p.size_median * std::exp(p.size_sigma * N01(rng));
			std::uint64_t amt = std::max<std::uint64_t>(
				1, static_cast<std::uint64_t>(sz + 0.5));

			std::uint64_t id = next_id++;
			feed.push_back(make_order(id, side, price, amt));
			++s.n_order;
			if (buy)
				++s.n_buy;
			else
				++s.n_sell;
			s.price_min = std::min(s.price_min, price);
			s.price_max = std::max(s.price_max, price);
			s.size_max = std::max(s.size_max, amt);
			s.size_sum += amt;

			// ---- match against the model book (price-time priority) ----
			std::uint64_t rem = amt;
			bool traded = false;
			if (buy) {
				while (rem > 0 && !asks.empty()) {
					auto lvl = asks.begin();
					if (lvl->first > price) break;
					auto& dq = lvl->second;
					while (rem > 0 && !dq.empty()) {
						std::uint64_t oid = dq.front();
						auto b = book.find(oid);
						if (b == book.end() || b->second.amt == 0) {
							dq.pop_front();
							continue;
						}
						std::uint64_t t = std::min(rem, b->second.amt);
						rem -= t;
						b->second.amt -= t;
						++s.sim_trades;
						s.sim_volume += t;
						traded = true;
						if (b->second.amt == 0) {
							dq.pop_front();
							remove_live(oid);
							book.erase(b);
						}
					}
					if (dq.empty()) asks.erase(lvl);
				}
			} else {
				while (rem > 0 && !bids.empty()) {
					auto lvl = std::prev(bids.end());  // highest bid
					if (lvl->first < price) break;
					auto& dq = lvl->second;
					while (rem > 0 && !dq.empty()) {
						std::uint64_t oid = dq.front();
						auto b = book.find(oid);
						if (b == book.end() || b->second.amt == 0) {
							dq.pop_front();
							continue;
						}
						std::uint64_t t = std::min(rem, b->second.amt);
						rem -= t;
						b->second.amt -= t;
						++s.sim_trades;
						s.sim_volume += t;
						traded = true;
						if (b->second.amt == 0) {
							dq.pop_front();
							remove_live(oid);
							book.erase(b);
						}
					}
					if (dq.empty()) bids.erase(lvl);
				}
			}
			if (traded) ++s.n_aggressive;

			// ---- rest the residual ----
			if (rem > 0) {
				book[id] = Resting{side, price, rem};
				(buy ? bids : asks)[price].push_back(id);
				add_live(id);
			}
		}
		s.max_depth = std::max<std::uint64_t>(s.max_depth, book.size());
	}
	s.mid_final = st.mid;

	// ------------------------------ write .bin ------------------------------
	const std::string bin_path = out_base + ".bin";
	{
		std::ofstream bf(bin_path,
						 std::ios::out | std::ios::binary | std::ios::trunc);
		bf.write(reinterpret_cast<const char*>(feed.data()),
				 static_cast<std::streamsize>(feed.size() * sizeof(Request)));
		if (!bf) {
			std::fprintf(stderr, "error writing %s\n", bin_path.c_str());
			return 1;
		}
	}

	// ------------------------------ write .txt ------------------------------
	const std::string txt_path = out_base + ".txt";
	{
		FILE* tf = std::fopen(txt_path.c_str(), "wb");
		if (!tf) {
			std::fprintf(stderr, "error writing %s\n", txt_path.c_str());
			return 1;
		}
		double avg_size =
			s.n_order ? static_cast<double>(s.size_sum) / s.n_order : 0.0;
		std::fprintf(tf, "# Order Book feed  |  scenario=%s  seed=%llu\n",
					 scen.c_str(), (unsigned long long)seed);
		std::fprintf(tf, "# requests=%llu  (price unit: integer ticks)\n",
					 (unsigned long long)count);
		std::fprintf(
			tf,
			"# orders=%llu (buy=%llu sell=%llu)  aggressive=%llu  "
			"partial_cancel=%llu  full_cancel=%llu\n",
			(unsigned long long)s.n_order, (unsigned long long)s.n_buy,
			(unsigned long long)s.n_sell, (unsigned long long)s.n_aggressive,
			(unsigned long long)s.n_partial, (unsigned long long)s.n_full);
		std::fprintf(tf,
					 "# sim_trades=%llu  sim_volume=%llu  avg_order_size=%.1f  "
					 "max_order_size=%llu\n",
					 (unsigned long long)s.sim_trades,
					 (unsigned long long)s.sim_volume, avg_size,
					 (unsigned long long)s.size_max);
		std::fprintf(tf,
					 "# max_resting_depth=%llu  mid: start=10000 min=%.0f "
					 "max=%.0f final=%.0f  order_price:[%llu,%llu]\n",
					 (unsigned long long)s.max_depth, s.mid_min, s.mid_max,
					 s.mid_final, (unsigned long long)s.price_min,
					 (unsigned long long)s.price_max);
		std::fprintf(tf, "#\n#%9s  %-14s %10s  %-4s %8s %10s\n", "seq", "type",
					 "order_id", "side", "price", "amt");

		char line[160];
		for (std::size_t i = 0; i < feed.size(); ++i) {
			const Request& r = feed[i];
			int n = 0;
			switch (r.header.type) {
				case RequestType::ORDER:
					n = std::snprintf(
						line, sizeof line,
						"%10zu  %-14s %10llu  %-4s %8llu %10llu\n", i, "ORDER",
						(unsigned long long)r.order.order_id,
						r.order.side == Side::BUY ? "BUY" : "SELL",
						(unsigned long long)r.order.price,
						(unsigned long long)r.order.amt);
					break;
				case RequestType::PARTIAL_CANCEL:
					n = std::snprintf(
						line, sizeof line,
						"%10zu  %-14s %10llu  %-4s %8s %10llu\n", i,
						"PARTIAL_CANCEL",
						(unsigned long long)r.partial_cancel.order_id,
						r.partial_cancel.side == Side::BUY ? "BUY" : "SELL", "-",
						(unsigned long long)r.partial_cancel.amt);
					break;
				case RequestType::FULL_CANCEL:
					n = std::snprintf(
						line, sizeof line,
						"%10zu  %-14s %10llu  %-4s %8s %10s\n", i,
						"FULL_CANCEL",
						(unsigned long long)r.full_cancel.order_id,
						r.full_cancel.side == Side::BUY ? "BUY" : "SELL", "-",
						"-");
					break;
			}
			std::fwrite(line, 1, static_cast<std::size_t>(n), tf);
		}
		std::fclose(tf);
	}

	std::printf(
		"[%s] %llu reqs -> %s (%llu bytes) + %s\n"
		"  orders=%llu (buy=%llu/sell=%llu) aggressive=%llu partial=%llu "
		"full=%llu\n"
		"  sim_trades=%llu sim_volume=%llu avg_size=%.1f max_size=%llu\n"
		"  max_resting_depth=%llu mid[min/max/final]=%.0f/%.0f/%.0f "
		"order_price[%llu,%llu]\n",
		scen.c_str(), (unsigned long long)count, bin_path.c_str(),
		(unsigned long long)(feed.size() * sizeof(Request)), txt_path.c_str(),
		(unsigned long long)s.n_order, (unsigned long long)s.n_buy,
		(unsigned long long)s.n_sell, (unsigned long long)s.n_aggressive,
		(unsigned long long)s.n_partial, (unsigned long long)s.n_full,
		(unsigned long long)s.sim_trades, (unsigned long long)s.sim_volume,
		s.n_order ? static_cast<double>(s.size_sum) / s.n_order : 0.0,
		(unsigned long long)s.size_max, (unsigned long long)s.max_depth,
		s.mid_min, s.mid_max, s.mid_final, (unsigned long long)s.price_min,
		(unsigned long long)s.price_max);
	return 0;
}
