/*
 * ********************************
 * **  GENERATED BY CLAUDE CODE  **
 * ********************************
 *
 * Generator for handwritten.bin — the binary twin of the hand-written test in
 * v1_baseline/test/test.h.
 *
 * Format: a flat stream of fixed-size records, each exactly sizeof(Request)
 * (48 bytes) in the machine's native layout, no delimiters. This is what the
 * fixed-size reader in stream::VectorInStream(const std::string&) consumes
 * (via istream::read, one sizeof(Request) chunk per record).
 *
 * Each record is zero-initialized before its active union member is populated,
 * so padding and the unused union tail are deterministic (clean git diffs /
 * reproducible bytes). The engine only reads the fields valid for each type, so
 * the zeroed tail is inert.
 *
 * Note: the layout is native x86-64 little-endian, matching this project's
 * fixed -O2 x86-64 target. The file is not portable across ABIs/endianness.
 *
 * Build & run (from repo root):
 *   g++ -std=c++23 -I common/include -O2 \
 *       -o /tmp/gen_handwritten v1_baseline/test/data/gen_handwritten.cpp
 *   /tmp/gen_handwritten v1_baseline/test/data/handwritten.bin
 */

#include <schema.h>

#include <cstdio>
#include <cstring>
#include <fstream>
#include <vector>

using namespace order_book::common;

static Request make_order(std::uint64_t id, Side side, std::uint64_t price,
						  std::uint64_t amt) {
	Request r;
	std::memset(&r, 0, sizeof r);
	r.order.type = RequestType::ORDER;
	r.order.len = sizeof(Order);
	r.order.order_id = id;
	r.order.side = side;
	r.order.price = price;
	r.order.amt = amt;
	return r;
}

static Request make_partial_cancel(std::uint64_t id, std::uint64_t amt) {
	Request r;
	std::memset(&r, 0, sizeof r);
	r.partial_cancel.type = RequestType::PARTIAL_CANCEL;
	r.partial_cancel.len = sizeof(PartialCancel);
	r.partial_cancel.order_id = id;
	r.partial_cancel.amt = amt;
	return r;
}

static Request make_full_cancel(std::uint64_t id) {
	Request r;
	std::memset(&r, 0, sizeof r);
	r.full_cancel.type = RequestType::FULL_CANCEL;
	r.full_cancel.len = sizeof(FullCancel);
	r.full_cancel.order_id = id;
	return r;
}

int main(int argc, char* argv[]) {
	if (argc != 2) {
		std::fprintf(stderr, "usage: %s OUTPUT_FILE\n", argv[0]);
		return 1;
	}

	// Mirrors the hand-written VectorInStream in v1_baseline/test/test.h.
	const std::vector<Request> reqs = {
		make_order(0, Side::BUY, 7, 10),
		make_order(1, Side::BUY, 8, 5),
		make_order(2, Side::BUY, 9, 1),
		make_order(3, Side::BUY, 9, 1),
		make_order(4, Side::BUY, 5, 3),
		make_order(5, Side::SELL, 6, 20),
		make_partial_cancel(5, 1),
		make_order(6, Side::SELL, 5, 2),
		make_full_cancel(5),
	};

	std::ofstream out(argv[1],
					  std::ios::out | std::ios::binary | std::ios::trunc);
	if (!out) {
		std::fprintf(stderr, "error: cannot open %s for writing\n", argv[1]);
		return 1;
	}
	for (const Request& r : reqs) {
		out.write(reinterpret_cast<const char*>(&r), sizeof(Request));
	}
	if (!out) {
		std::fprintf(stderr, "error: write failed\n");
		return 1;
	}

	std::printf("wrote %zu records (%zu bytes) to %s\n", reqs.size(),
				reqs.size() * sizeof(Request), argv[1]);
	return 0;
}
